spack:
  specs:
  - bc
  - bison
  - bzip2
  - cmake
  - cppcheck
  - curl
  - flex
  - ffmpeg
  - flex@2.5.39
  - emacs
  - git
  - gdb
  - gnuplot
  - gnutls
  - htop
  - imagemagick
  - libxml2
  - likwid
  - ninja
  - mercurial
  - makedepend
  - patch
  - pkg-config
  - python
  - python@2.7.18
  - rsync
  - screen
  - stow
  - strace
  - texinfo
  - texlive
  - tmux
  - unzip
  - vim
  - wget
  - zsh
  #- global
  #- xterm
  view: false
