spack:
  specs:
  - catch2@2.13.4
  - fmt@7.1.3
  # - googletest@1.10.0
  - gsl@2.6
  # - abseil-cpp@20200923.2
  # - boost@1.76.0
  # - snappy@1.1.8
  # - protobuf@3.12.2
  # - glog@0.4.0
  # - capnproto@0.7.0
  # - cppzmq@4.6.0
  # - libzmq@4.3.3
  # - gflags@2.1.2
  # - yaml-cpp@0.6.3
  # - eigen@3.3.8
  # - ceres-solver@2.0.0
  # - zlib@1.2.11
  # - opencv@3.1.0
  # - pcl@1.11.1
  # - flann@1.9.1
  # - libpng@1.6.37
  # - yarn@1.22.4
  # - llvm@11.0.0
  # - cuda

  config:
    # This is the path to the root of the Spack install tree.
    # You can use $spack here to refer to the root of the spack instance.
    install_tree:
      projections:
        all: ${PACKAGE}/${VERSION}
      root: /home/amin/applications_spack
    # Temporary locations Spack can try to use for builds
    # The build stage can be purged with `spack purge --stage`.
    build_stage: $tempdir/$user/spack

    # Cache directory for miscellaneous files, like the package index.
    # This can be purged with `spack purge --misc-cache`
    misc_cache: ~/.spack/cache

  modules:
    default:
      lmod:
        core_compilers:
        - gcc@9.3.0
