spack:
  specs:
  - catch2@2.13.4
  - fmt@7.1.3
  - googletest@1.10.0
  - gsl@2.6
  - abseil-cpp@20200923.2
  - boost@1.76.0
  - cppzmq@4.6.0
  - libzmq@4.3.3
  - eigen@3.3.8
  - python@3.6.9
  - cuda@10.2.89
  - llvm@13.0.0
  - npm@6.14.9
  - dotnet-core-sdk@5.0.4
  - doxygen@1.8.14
  - openjdk@1.8.0_265-b01
  - nlohmann-json@3.10.4
  # - openmpi@4.1.1
  # - capnproto@0.7.0
  # - ceres-solver@2.0.0
  # - flann@1.9.1
  # - gflags@2.1.2
  # - glog@0.4.0
  # - libpng@1.6.37
  # - lmod@8.5.6
  # - opencv@3.1.0
  # - pcl@1.11.1
  # - protobuf@3.12.2
  # - snappy@1.1.8
  # - yaml-cpp@0.6.3
  # - yarn@1.22.4
  # - zlib@1.2.11


  config:
    # This is the path to the root of the Spack install tree.
    # You can use $spack here to refer to the root of the spack instance.
    install_tree:
      projections:
        all: ${PACKAGE}/${VERSION}
      root: /home/amin/applications
    # Temporary locations Spack can try to use for builds
    # The build stage can be purged with `spack purge --stage`.
    build_stage: $tempdir/$user/spack
    module_roots:
      lmod: /home/amin/applications/lmod/lmod/modulefiles/Core

    # Cache directory for miscellaneous files, like the package index.
    # This can be purged with `spack purge --misc-cache`
    misc_cache: ~/.spack/cache

  modules:
    enable:
    - lmod
    lmod:
      all:
        filter:
          environment_blacklist: ['CPATH', 'LIBRARY_PATH']  
      hash_length: 0
      projections:
          all: '{name}/{version}'
      core_compilers:
      - gcc@9.3.0
