spack:
  specs:
    - binutils 
    - cuda@11.7.1
    - cuda@11.6.2
    - cuda@11.5.2
    - cuda@11.4.4
    - cuda@11.3.1
    - cuda@11.2.2
    - gcc@12.2.0
    - gcc@11.3.0
    - gcc@10.4.0
    - gcc@9.5.0
    - gcc@8.5.0
    - gcc@7.5.0
    - go@1.18.4
    - llvm@15.0.2
    - llvm@14.0.6
    - llvm@13.0.1
    - llvm@12.0.1
  view: False
