# permissions for end users to edit spacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: build-editor-role
rules:
- apiGroups:
  - multiarch.builder.io
  resources:
  - builds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multiarch.builder.io
  resources:
  - builds/status
  verbs:
  - get
