spack:
  compilers:
  - compiler:
      spec: clang@=15.0.7
      paths:
        cc: /usr/lib64/ccache/clang
        cxx: /usr/lib64/ccache/clang++
        f77: null
        fc: null
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@=10.3.1
      paths:
        cc: /usr/tce/bin/gcc
        cxx: /usr/tce/bin/g++
        f77: /usr/tce/bin/gfortran
        fc: /usr/tce/bin/gfortran
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@=8.5.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: intel@=2021.6.0
      paths:
        cc: /usr/tce/packages/intel-classic/intel-classic-2021.6.0-magic/bin/icc
        cxx: /usr/tce/packages/intel-classic/intel-classic-2021.6.0-magic/bin/icpc
        f77: /usr/tce/packages/intel-classic/intel-classic-2021.6.0-magic/bin/ifort
        fc: /usr/tce/packages/intel-classic/intel-classic-2021.6.0-magic/bin/ifort
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  packages:
    all:
      providers:
        mpi: [openmpi]
    binutils:
      externals:
      - spec: binutils@2.30.119
        prefix: /usr
    coreutils:
      externals:
      - spec: coreutils@8.30
        prefix: /usr
    diffutils:
      externals:
      - spec: diffutils@3.6
        prefix: /usr
    findutils:
      externals:
      - spec: findutils@4.6.0
        prefix: /usr
    gawk:
      externals:
      - spec: gawk@4.2.1
        prefix: /usr
    openmpi:
      buildable: false
      externals:
      - spec: openmpi@4.1.2 %gcc@10.3.1
        prefix:  /usr/tce/packages/openmpi/openmpi-4.1.2-gcc-10.3.1/
      - spec: openmpi@4.1.2 %clang@14.0.6
        prefix:  /usr/tce/packages/openmpi/openmpi-4.1.2-clang-14.0.6/
    openssh:
      externals:
      - spec: openssh@8.0p1
        prefix: /usr
    openssl:
      externals:
      - spec: openssl@1.1.1k
        prefix: /usr
    tar:
      externals:
      - spec: tar@1.30
        prefix: /usr
    autoconf:
      externals:
      - spec: autoconf@2.69
        prefix: /usr
    automake:
      externals:
      - spec: automake@1.16.1
        prefix: /usr
    bison:
      externals:
      - spec: bison@3.0.4
        prefix: /usr
    ccache:
      externals:
      - spec: ccache@3.7.7
        prefix: /usr
    cmake:
      externals:
      - spec: cmake@3.20.2
        prefix: /usr
      - spec: cmake@3.23.1
        prefix: /usr/tce
    curl:
      externals:
      - spec: curl@7.61.1+gssapi+ldap+nghttp2
        prefix: /usr
    cvs:
      externals:
      - spec: cvs@1.11.23
        prefix: /usr
    doxygen:
      externals:
      - spec: doxygen@1.8.14+graphviz~mscgen
        prefix: /usr
    flex:
      externals:
      - spec: flex@2.6.1+lex
        prefix: /usr
    git:
      externals:
      - spec: git@2.39.3+tcltk
        prefix: /usr
      - spec: git@2.29.1+tcltk
        prefix: /usr/tce
    git-lfs:
      externals:
      - spec: git-lfs@2.11.0
        prefix: /usr/tce
    gmake:
      externals:
      - spec: gmake@4.2.1
        prefix: /usr
    groff:
      externals:
      - spec: groff@1.22.3
        prefix: /usr
    libtool:
      externals:
      - spec: libtool@2.4.6
        prefix: /usr
    m4:
      externals:
      - spec: m4@1.4.18
        prefix: /usr
    pkgconf:
      externals:
      - spec: pkgconf@1.4.2
        prefix: /usr
    slurm:
       externals:
       - spec: slurm@22.05.08
         prefix: /usr
         sysconfdir: /etc/slurm
       buildable: False
    subversion:
      externals:
      - spec: subversion@1.10.2
        prefix: /usr
    swig:
      externals:
      - spec: swig@3.0.12
        prefix: /usr
    texinfo:
      externals:
      - spec: texinfo@6.5
        prefix: /usr
  specs:
  - beatnik @develop %gcc@10.3.1
