spack:
  specs:
    - binutils 
    - cuda@11.6.2
    - cuda@11.5.1
    - cuda@11.4.4
    - cuda@11.3.1
    - cuda@11.2.2
    - cuda@11.0.3
    - cuda@10.2.89
    - gcc@11.2.0
    - gcc@10.3.0
    - gcc@9.4.0
    - gcc@8.5.0
    - gcc@7.5.0
    - go@1.17.7
    - llvm@14.0.0
    - llvm@13.0.1
    - llvm@12.0.0
    - llvm@11.1.0
    - llvm@10.0.0
    - intel-parallel-studio@cluster.2020.4
    - intel-parallel-studio@cluster.2019.5
    - intel-parallel-studio@cluster.2018.4
    - pgi@20.04
    - pgi@19.10
  view: False
