name: Generate catalog

on:
  workflow_dispatch:
  schedule:
    - cron: 0 5 * * *

jobs:
  generate-catalog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        run: conda create --quiet --name stacks
      - name: generate-catalog
        shell: bash -l {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate stacks
          conda install scikit-learn pandas
          pip install jinja2 pygithub gitpython pyaml

          python scripts/generate-catalog.py
          python scripts/generate-graph-data.py
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add _stacks/
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@057a6ba835d986bfe495dd476a6c4db1d5f9503c
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
